let firstName='Srividhya';
let companyName='Testleaf';
let mobileNumber=9940065939;
let isAutomation=false;
let hasPlaywright;
console.log(firstName);
console.log(typeof firstName);
console.log(companyName);
console.log(typeof companyName);
console.log(mobileNumber);
console.log(typeof mobileNumber);
console.log(isAutomation);
console.log(typeof isAutomation);
console.log(hasPlaywright);
console.log(typeof hasPlaywright);
